export enum ActionType {
  FETCH_PROPERTY_LIST = "FETCH_PROPERTY_LIST",
  FETCH_PROPERTY_LIST_SUCCESS = "FETCH_PROPERTY_LIST_SUCCESS",
  FETCH_PROPERTY_LIST_ERROR = "FETCH_PROPERTY_LIST_ERROR",

  FETCH_FILTERS_LIST = "FETCH_FILTERS_LIST",
  FETCH_FILTERS_LIST_SUCCESS = "FETCH_FILTERS_LIST_SUCCESS",
  FETCH_FILTERS_LIST_ERROR = "FETCH_FILTERS_LIST_ERROR",
}
